### ISSUE TITLE
New review broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#573]
@EldonReturn, @jhpedemonte

WIth today's auto build, immediately upon invoking the New Review... command from the main menu bar, the following things appear in the Chrome console:

27862unknown error: status=undefined
dojo.js:1445TypeError: Object [object Object] has no method 'getChildren'
dojo.js:1445TypeError: Object [object Object] has no method 'getChildren'
dojo.js:1445ReferenceError: result is not defined

**Comment by peller** [comment]
My bad. I didn't notice the exception.  We need more error handlers.  @childsb: It seems that every xhr ought to have both load and error callbacks (see `davinci.model.Resource.Folder.prototype.getChildren`)

**Comment by jhpedemonte** [comment]
You can also use the `handle` property, which gets invoked for both the `load` and `error` cases.

**Comment by peller** [comment]
This appears to be working on HEAD now

**Comment by JonFerraiolo** [comment]
Not working for me. I just pulled the latest from GitHub, cleared my browser cache, and restarted my Eclipse server, and I still get this when I open a New Review (using Mac/Chrome)

315unknown error: status=undefined
app/dojo/./_base/Deferred.js:213TypeError: Object [object Object] has no method 'getChildren'
app/dojo/./_base/Deferred.js:213TypeError: Object [object Object] has no method 'getChildren'
app/dojo/./_base/Deferred.js:213ReferenceError: result is not defined

**Comment by jhpedemonte** [comment]
Seeing the same as Jon.  Pulled daily build from this morning [1].  Ran using `./maqetta.local.mac.command`. Loaded in browser, opened **Sample1.html**, then selected **New**->**Review...** and got errors in console.

The **_unknown error: status**_ warning is from `Runtime.js.serverJSONRequest()`, the 2nd `console.warn`.

The debugger then traps in **davinci.review.actions.ReviewFileTreeModel**'s `getChildren()`.  The 2nd line is `parentItem.getChildren(onComplete, true)` -- that object has no `getChildren` property.

`parentItem` is of type **davinci.model.Resource.File**, where `name` is "SampleJs.js" and `elementType` is "File".

Here's the stack trace:

> dojo.declare.getChildren() at app/dojo/../davinci/review/actions/ReviewFileTreeModel.js:20
> dojo.declare._expandNode() at davinci.js:45337
> isExpandable() at davinci.js:45337
> dojo.mixin.forEach() at dojo.js:892
> dojo.declare.setChildItems() at davinci.js:45337
> def() at davinci.js:45337
> (anonymous function)() at davinci.js:45337
> dojo.mixin.forEach() at dojo.js:892
> davinci.Runtime.serverJSONRequest.load() at davinci.js:45337
> dojo.hitch() at dojo.js:758
> dojo._ioSetArgs.err() at dojo.js:4425
> _102() at dojo.js:1457
> _100() at dojo.js:1444
> dojo.Deferred.resolve.callback() at dojo.js:1482
> _102() at dojo.js:1466
> _100() at dojo.js:1444
> dojo.Deferred.resolve.callback() at dojo.js:1482
> _28d() at dojo.js:4586
> _286.func() at dojo.js:4503
> _286() at dojo.js:4523
> _25c._ioWatch() at dojo.js:4573
> dojo.xhr() at dojo.js:4650
> dojo.xhrGet() at dojo.js:4655
> dojo.mixin.serverJSONRequest() at davinci.js:45337
> davinci.model.Resource.Folder.getChildren() at davinci.js:45337
> dojo.declare.getChildren() at app/dojo/../davinci/review/actions/ReviewFileTreeModel.js:20
> dojo.declare._expandNode() at davinci.js:45337
> (anonymous function)() at davinci.js:45337
> dojo.hitch() at dojo.js:758
> dojo.declare.getRoot() at app/dojo/../davinci/review/actions/ReviewFileTreeModel.js:13
> dojo.declare._load() at davinci.js:45337
> dojo.declare.postCreate() at davinci.js:45337
> dojo.declare.create() at dijit.js:1844
> _a6() at dojo.js:1084
> dojo.declare.create() at dijit.js:2154
> dojo.declare.postscript() at dijit.js:1814
> a() at dojo.js:1181
> dojo.declare._initPage2() at app/dojo/../davinci/review/widgets/PublishWizard.js:121
> dojo.declare.postCreate() at app/dojo/../davinci/review/widgets/PublishWizard.js:58
> dojo.declare.create() at dijit.js:1844
> _a6() at dojo.js:1084
> dojo.declare.create() at dijit.js:2154
> dojo.declare.postscript() at dijit.js:1814
> a() at dojo.js:1181
> dojo.declare.run() at app/dojo/../davinci/review/actions/PublishAction.js:46
> dojo.mixin.publish() at app/dojo/../davinci/review/Runtime.js:47
> (anonymous function)() at line 1dojo.mixin._runAction() at davinci.js:45337
> dojo._hitchArgs() at dojo.js:737
> dojo.declare.onItemClick() at davinci-common.js:2482
> dojo.declare._onClick() at davinci-common.js:2256
> dojo.hitch() at dojo.js:754

[1] Version: Preview 2
Date: Jun 21, 2011 7:02:04 AM
Build: 0343f594cc15db4...

**Comment by EldonReturn** [comment]
I tried to reproduce this bug with no luck today. But I observed a couple of suspicious things.
1. Line 73 in SystemFileList.java: file does not has such a method getTotalSpace() in Java 1.5
2. The call sequence:

dojo.declare._expandNode() at davinci.js:45337
 isExpandable() at davinci.js:45337
 dojo.mixin.forEach() at dojo.js:892
 dojo.declare.setChildItems() at davinci.js:45337
 def() at davinci.js:45337

shows that the exception is thrown when the tree is setting the default open folders. So I guess the problem maybe resolved by clearing cookies (clearing cache and clearing cookies are.two options in Chrome)

**Comment by JonFerraiolo** [comment]
With both today's nightly build and running from http://localhost:50000, and then after pulling latest from GitHub and launching from Eclipse and running on localhost, I'm still seeing the following in the Mac/Chrome console:

```
Runtime.js:315unknown error: status=undefined
app/dojo/./_base/Deferred.js:213TypeError: Object [object Object] has no method 'getChildren'
app/dojo/./_base/Deferred.js:213TypeError: Object [object Object] has no method 'getChildren'
app/dojo/./_base/Deferred.js:213ReferenceError: result is not defined
```

**Comment by JonFerraiolo** [comment]
For both Chrome and Firefox4, I ran into this problem, but when I cleared localhost cookies, the problem went away. New Review is working for me again for both Chrome and Firefox.

**Comment by peller** [comment]
So we'll need a way to transition the cookies.  see #599
