### ISSUE TITLE
Color changes don't wait for OK, are immediate

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#598]
@billreed63

(revising bug report - I'm seeing this in page editor, too, not just theme editor)

The theme editor commits color property changes immediately upon bringing up the color picker. To reproduce:
- Clone a new theme
- Open theme editor on the new theme
- Select Dialog. Using color picker, change background color to blue or whatever.
- Select ContentPane. Bring up color picker.

Result=> Immediately the ContentPane's background changes to the most recently used color.

Another case (using Mac/Chrome):
- New HTML File
- Add 2 buttons
- Select first button. Change 'color' property to a red color using color picker.
- Select second button. Bring up color picker.

Result=> Second button immediately changes to the color used for the first button (before hitting OK or anything)

**Comment by jhpedemonte** [comment]
I cannot reproduce.

For one thing, trying to select **Dialog** in the **Theme Editor** results in an error:

```
Uncaught TypeError: Cannot read property 'property' of undefined         WidgetProperties.js:42
```

Even then, I tried to use other widgets, but I didn't see the immediate selection of background color.

**Comment by JonFerraiolo** [comment]
I just reproduced it with latest code from GitHub on Mac/Chrome.

**Comment by JonFerraiolo** [comment]
I put a breakpoint in StyleCommand.js execute() and looked at stack trace. It looks like ColorPicker.js's _onChange() function is getting called when the ColorPicker is first launched, which then triggers various calls that end up in StyleCommand.

**Comment by jhpedemonte** [comment]
OK, now I see it.  I missed the reference to the **Color Picker** -- I was just selecting **Red** from the drop down list. Upping priority to **Med**.

**Comment by childsb** [comment]
Fixed with commit 375e645ae1323989bffdb42bc9b500cf8d9eaf84

**Comment by JonFerraiolo** [comment]
I pulled down latest sources, and my git log shows commit 375e645 as being on my system, and I cleared my browser cache on both FF and Chrome. After all of this, on both FF and Chrome, when I try the example listed at top of bug report (two buttons, ...), I'm still seeing the second button's text changing color immediately upon bringing up color picker.
- New HTML File
- Add 2 buttons
- Select first button. Change 'color' property to a red color using color picker.
- Select second button. Bring up color picker.

Result=> Second button immediately changes to the color used for the first button (before hitting OK or anything)

**Comment by childsb** [comment]
I think this is because you're modifying the theme rule for button with the first change.

if i add a button, then a text box i can change bg color of button and select the text box with no effect.

**Comment by JonFerraiolo** [comment]
Sorry about reopening. When I change 'color' on a Button, the element.style gets updated, not the theme.

**Comment by childsb** [comment]
jon, are you sure? element.style isn't an option for "Button" with background-color in the cascade..  The top/default entry is [theme](copy and paste of cascade with a button selected):

[theme] .claro .dijitButton .dijitButtonNode, .claro .dijitDropDownButton .dijitButtonNode, .claro .dijitComboButton .dijitButtonNode, .claro .dijitToggleButton .dijitButtonNode (themes/claro/form/Button.css line:undefined)
background-color:#e4f2ff;

[theme] .claro .dijitButtonNode (themes/claro/form/Button.css line:undefined)

[theme] .dijitButtonNode, .dijitButtonNode \* (themes/claro/dijit.css line:undefined)

[theme] .dijitButtonNode (themes/claro/dijit.css line:undefined)

[theme] .dijitInline (themes/claro/dijit.css line:undefined)

[theme] .dijitReset (themes/claro/dijit.css line:undefined)

**Comment by childsb** [comment]
oh "color" as in the font color. sorry let me test..

**Comment by childsb** [comment]
Fixed this with checkin d64020486d37a52c22bca2c405e80fff1e021644
