### ISSUE TITLE
Default Project name has space

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#810]
(1) I suggest using a default project name without any spaces or special characters, if only because they will make life harder for the user outside the tool (e.g. in the shell)

(2) I noticed that if I drag an image like SampleBanner.jpg to the canvas, the url created in the source is not URI encoded -- it should read something like Sample%20Project.  URIEncoding should be used regardless of the default project name.

(3) Even if it's encoded, there's a mismatch in the image dnd example... the SampleBanner.jpg resource only works if it is referenced without the "Default%20Project" in the path, but simply as "SampleBanner.jpg" (preferably normalized without the "./")

**Comment by JonFerraiolo** [comment]
I would go with the name "project1", and then allow the user to change the name later. I've been using file1, folder1, etc. for other parts of the product. So for consistency, we would use "project1". One small advantage to this naming approach is that when a user needs to create a 2nd and 3rd, we can compute a suggested automatic name such as file2.html, file3.html, using proposed name logic in Resource.js.

**Comment by childsb** [comment]
Fixed with checkin 27650e38cbac86cb3e90

**Comment by peller** [comment]
please also consider (2) -- lower priority, but somewhere we're not escaping urls -- and I'll retest (3)

**Comment by childsb** [comment]
this sounds like a bug with DND, and i'm guessing also an issue with preview 2 where you to create a file in folder with a space, then drag an image to its canvas.  (.\project one\file1.html)  

how is DND generating the URL?

**Comment by peller** [comment]
I confirmed that (3) is still a problem... simply dragging the SampleBanner.jpg to the canvas results in a broken image.  It seems that the project name (e.g. project1) should not be part of the relative url.  Also, the leading "./" should be removed.

> how is DND generating the URL?

Yeah, I suppose we could escape it right away.  I think that happens in davinci.ve.palette.ImageDragSource.

**Comment by jhpedemonte** [comment]
See #862 for more info on the issue with dragging image on to page.

**Comment by childsb** [comment]
duplicate of 862, moving this issue there.
