### ISSUE TITLE
Loading hang when changing button label in source pane (split view)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#927]
@peller, @waynevicknair

Using Win/FF6 within today's build (http://maqetta.org/nightly/maqetta-20110906-0603.zip), I opened up Sample1.html, went into split view, scrolled to bottom, and for the Button that is inside the absolutely positioned ContentPane, I attempted to change the label from "Add" to "a longish sort of string". This caused the "Loading..." message to appear in design pane, but the "Loading..." message never goes away. If I refresh the browser, my changes are now visible in Sample1.html, although there might be some other problems with the file.

**Comment by billreed63** [comment]
was throwing exception if widget was not in library..  added check if (library)

**Comment by jhpedemonte** [comment]
I'm not completely sold on the fix.  Seems like it might be covering a deeper issue.

If I break at that location when `library` is null, the widget type is **dijit._MasterTooltip**.  Why is that widget here?  It's not on the page.

Further up in the stack, I notice that a set of widgets is returned from `Context.getTopWidgets()`.  It returns an array of length 3, consisting of **TabContainer**, **ContentPane** and **dijit._MasterTooltip**.  There is no tooltip in Sample1.html.  Where is it coming from?

**Comment by billreed63** [comment]
It is being added by dojo when it expands the widgets, I have seen this before with another widget. This all gets back to we should be working off the model not the DOM.

**Comment by peller** [comment]
dijit._MasterTooltip is a singleton instantiated whenever there is a dijit.Tooltip on the page. when a dijit.Tooltip is activated, it positions the singleton and makes it visible.  So interestingly, you don't have to instantiate dijit.Tooltip, just require the code to get a MasterTooltip.  Hmm... ok, I still can't explain why it's there on sample1.html.

**Comment by jhpedemonte** [comment]
`getTopWidgets()` goes through looking for any node that has a `_dvWidget` property.  Why does **dijit._MasterTooltip** have that property?

**Comment by peller** [comment]
the attach code _should_ skip widgets beginning with "_" (see Context.js attach() line 162)

**Comment by JonFerraiolo** [comment]
Does this skipping logic get invoked as part of page open process?

**Comment by jhpedemonte** [comment]
The thing is, I put a breakpoint on every place that adds `_dvWidget` and I didn't see it get hit for _MasterTooltip.  I'm missing something.

**Comment by peller** [comment]
yes, `attach()` is what establishes all of the widgets on page open, IIRC.

**Comment by jhpedemonte** [comment]
OK, I was blind.  This is all thanks to `getWidget()`, which creates a widget instance when called from `Context._attachChildren()`, which itself parses over every DOM node in the doc.

I'll close this again, since we have other bugs to handle the issues with `getWidget()`.

**Comment by peller** [comment]
right... getWidget() has major side-effects.  We ought to rename the method.

**Comment by JonFerraiolo** [comment]
When I was working on the "fixed" property for ScrollableView, I ended up splitting getChildren into 2 separate routines, findChildren and getChildren. The findChildren returns the list of child nodes that ultimately will become widgets, and getChildren returns the list of child nodes that have become widgets. I did a findChildren at document load and then called whatever getWidget() calls to actually create the widgets, and invoked getChildren in a separate block of code. We need something like that.
